safe: true
lsi: false
pygments: true
source: .
destination: ./_site
title: Michele Pratusevich is a pathological dilettante
author: 
  name: Michele Pratusevich
  email: michele.pratusevich@gmail.com

production_url : http://mprat.org

port: 4000
markdown: kramdown
   # use_coderay: true
comments: true