safe: true
markdown: kramdown
destination: ./_site
highlighter: rouge
source: .
baseurl: ""
title: Michele Pratusevich is a pathological dilettante
author:
  name: Michele Pratusevich
  email: michele.pratusevich@gmail.com
production_url : http://mprat.org
comments: true
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
